#!/bin/bash

. /start-utils
isDebugging && set -x
set -e

if ! [[ -v FTB_MODPACK_ID ]]; then
  log "ERR FTB_MODPACK_ID is required with TYPE=FTB"
  exit 1
fi

if ! [[ ${FTB_MODPACK_ID} =~ [0-9]+ ]]; then
  log "ERR FTB_MODPACK_ID needs to be numeric"
  exit 1
fi

ftbInstaller=/data/ftb-installer
if ! [[ -e "${ftbInstaller}" ]]; then
  log "Downloading FTB installer"
  curl -fsSL https://api.modpacks.ch/public/modpack/1/1/server/linux -o "${ftbInstaller}"
  chmod +x "${ftbInstaller}"
fi

if ! [[ -v FTB_MODPACK_VERSION_ID ]]; then
  FTB_MODPACK_VERSION_ID="--latest"
elif ! [[ ${FTB_MODPACK_VERSION_ID} =~ [0-9]+ ]]; then
  log "ERR FTB_MODPACK_VERSION_ID needs to be numeric"
  exit 1
fi

rm -rf forge*jar mods config libraries defaultconfigs changelogs

${ftbInstaller} ${FTB_MODPACK_ID} ${FTB_MODPACK_VERSION_ID} --noscript --auto
rm -f forge*installer.jar

isDebugging && cat version.json
forgeVersion=$(jq -r '.targets[] | select(.name == "forge") | .version' version.json)
mcVersion=$(jq -r '.targets[] | select(.name == "minecraft") | .version' version.json)

variants=(
  forge-${mcVersion}-${forgeVersion}.jar
  forge-${mcVersion}-${forgeVersion}-universal.jar
  forge-${mcVersion}-${forgeVersion}-${mcVersion}-universal.jar
)
for f in ${variants[@]}; do
  if [ -f $f ]; then
    export SERVER=$f
    break
  fi
done
if ! [ -v SERVER ]; then
  log "ERROR unable to locate the installer forge server jar"
  ls *.jar
  exit 2
fi

# Continue to Final Setup
exec /start-finalSetup01World "$@"
